db:
  image: postgres:9.4

rabbitmq:
 image: rabbitmq:3.5.4
 ports:
    - "15672:15672"
    - "5672:5672"

celery:
 build: .
 working_dir: /code
 command:  su -m myuser -c "sleep 6 &&  celery -A test_drive worker --loglevel=info"
 environment:
    - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    
 links:
    - rabbitmq
    - db
 volumes:
    - .:/code

flower:
  build: .
  environment:
    - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    
  working_dir: /code
  command: su -m myuser -c "sleep 6 && celery flower -A test_drive --port=5555"
  volumes:
    - .:/code
  ports:
    - "5555:5555"
  links:
    - db
    - rabbitmq
    
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  environment:
    - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - rabbitmq